version: '3.8'

services:
  app:
    user: user
    build:
      context: .
      args:
        UID: "${UID}"
        GID: "${GID}"
    volumes:
      - app-data:/home/user
    environment:
      - UID=${UID}
      - GID=${GID}


volumes:
  app-data: